# Generated by Django 6.0.5 on 2026-05-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_normaluserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluserprofile',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
